// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('alpCustom').directive("breadcrumbs", [
    'LIB_URL', function(LIB_URL) {
      return {
        restrict: "E",
        replace: true,
        templateUrl: function(elm, attrs) {
          return attrs.templateUrl || LIB_URL + 'directives/breadcrumbs/breadcrumbs.html';
        },
        scope: {
          'fetch': '&',
          'list': '='
        },
        controller: [
          "$scope", "$element", function($scope, $element) {
            var init;
            init = function() {
              var root;
              $scope.list = [];
              root = {
                id: 'root',
                name: 'Main'
              };
              $scope.list.push(root);
            };
            init();
            $scope.process = function(id) {
              var b, list, _i, _len, _ref;
              if (id === 'root') {
                init();
                $scope.fetch();
              } else {
                list = [];
                _ref = $scope.list;
                for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                  b = _ref[_i];
                  list.push(b);
                  if (b.id === id) {
                    break;
                  }
                }
                $scope.list = list;
                $scope.fetch({
                  id: id
                });
              }
            };
          }
        ]
      };
    }
  ]);

}).call(this);
