// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('alpCustom').directive("selectOption", [
    'LIB_URL', function(LIB_URL) {
      return {
        restrict: "E",
        replace: true,
        templateUrl: function(elm, attrs) {
          return attrs.templateUrl || LIB_URL + 'directives/select-option/select-option.html';
        },
        scope: {
          'model': '=',
          'list': '='
        },
        compile: function(cElement, cAttributes, transclude) {
          return {
            pre: function(scope, elm, attrs) {
              scope.expression = attrs.swOptions;
            },
            post: function(scope, elm, attrs) {}
          };
        }
      };
    }
  ]);

}).call(this);
