// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('alpCustom').service('hierarchialTreeService', [
    function() {
      this.map = [];
      this.exists = function(name) {
        return this.map.indexOf(name) !== -1;
      };
      this.put = function(name) {
        return this.map[name] = {
          component: null,
          fn: null
        };
      };
      return this;
    }
  ]);

  angular.module('alpCustom').directive("hierarchialTree", [
    'hierarchialTreeService', function(hierarchialTreeService) {
      return {
        restrict: "E",
        replace: true,
        template: "<ul><hierarchial-tree-node ng-repeat='c in list' item='c' uid='{{passUidToMember}}' content='{{content}}'></hierarchial-tree-node></ul>",
        scope: {
          id: '=',
          fetch: '&',
          uid: '@',
          component: '='
        },
        controller: ["$scope", "$element", function($scope, $element) {}],
        link: function(scope, elm, attrs) {
          var fetch, name;
          scope.content = attrs.content;
          name = '';
          if (scope.uid) {
            name = scope.uid;
          } else {
            name = 'uid' + scope.$id;
            if (!hierarchialTreeService.exists(name)) {
              hierarchialTreeService.put(name);
              hierarchialTreeService.map[name].fn = function(fn, id) {
                if (id) {
                  return scope.fetch({
                    id: id,
                    fn: fn
                  });
                } else {
                  return scope.fetch({
                    id: null,
                    fn: fn
                  });
                }
              };
              scope.$watch(function() {
                return hierarchialTreeService.map[name].component;
              }, function(newvalue, oldvalue) {
                return scope.component = newvalue;
              }, true);
            }
          }
          scope.passUidToMember = name;
          fetch = function(fn, id) {
            if (id) {
              return hierarchialTreeService.map[name].fn(function(data) {
                return fn(data);
              }, id);
            } else {
              return hierarchialTreeService.map[name].fn(function(data) {
                return fn(data);
              });
            }
          };
          if (scope.id) {
            return fetch(function(data) {
              return scope.list = data;
            }, scope.id);
          } else {
            return fetch(function(data) {
              return scope.list = data;
            });
          }
        }
      };
    }
  ]);

  angular.module('alpCustom').directive("hierarchialTreeNode", [
    '$templateRequest', '$sce', '$compile', 'hierarchialTreeService', function($templateRequest, $sce, $compile, hierarchialTreeService) {
      return {
        restrict: "E",
        replace: true,
        scope: {
          item: '=',
          uid: '@'
        },
        controller: ["$scope", "$element", function($scope, $element) {}],
        link: function(scope, elm, attrs) {
          var templateUrl;
          scope.select = function() {
            return hierarchialTreeService.map[scope.uid].component = angular.copy(scope.item);
          };
          templateUrl = $sce.getTrustedResourceUrl(attrs.content);
          $templateRequest(templateUrl).then(function(t) {
            var template;
            template = "<li ng-click='select()'> " + t + " <button ng-show='item.hasChildren && !item.loaded' ng-click='load()'>+</button><button ng-show='item.loaded && !item.open' ng-click='expand()'>+</button><button ng-show='item.loaded && item.open' ng-click='collapse()'>-</button></li>";
            elm.html(template).show();
            $compile(elm.contents())(scope);
          }, function() {
            var template;
            console.log('error');
            template = "<li ng-click='select()'> {{item}} <button ng-show='item.hasChildren && !item.loaded' ng-click='load()'>+</button><button ng-show='item.loaded && !item.open' ng-click='expand()'>+</button><button ng-show='item.loaded && item.open' ng-click='collapse()'>-</button></li>";
            elm.html(template).show();
            $compile(elm.contents())(scope);
          });
          scope.load = function() {
            if (scope.item.hasChildren) {
              scope.item.loaded = true;
              scope.item.open = true;
              elm.append('<hierarchial-tree id="item.id" uid="{{uid}}" ng-show="item.open" content="' + attrs.content + '"></hierarchial-tree>');
              $compile(elm.contents())(scope);
            }
          };
          scope.expand = function() {
            return scope.item.open = true;
          };
          return scope.collapse = function() {
            return scope.item.open = false;
          };
        }
      };
    }
  ]);

}).call(this);
