// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('alpCustom').service('hierarchialTreeService', [
    function() {
      this.map = [];
      this.exists = function(name) {
        return this.map.indexOf(name) !== -1;
      };
      this.put = function(name) {
        return this.map[name] = {
          component: null,
          fn: null,
          list: []
        };
      };
      return this;
    }
  ]);

  angular.module('alpCustom').directive("hierarchialTree", [
    'hierarchialTreeService', 'LIB_URL', function(hierarchialTreeService, LIB_URL) {
      return {
        restrict: "E",
        replace: true,
        template: "<ul class='tree'><hierarchial-tree-node ng-repeat='c in list' item='c' uid='{{passUidToMember}}' content='{{content}}' depth='{{depth}}'></hierarchial-tree-node></ul>",
        scope: {
          id: '=',
          fetch: '&',
          uid: '@',
          depth: '@',
          component: '='
        },
        controller: ["$scope", "$element", function($scope, $element) {}],
        link: function(scope, elm, attrs) {
          var fetch, name;
          console.log(LIB_URL);
          if (!scope.depth) {
            scope.depth = 0;
          }
          scope.content = attrs.content;
          name = '';
          if (scope.uid) {
            name = scope.uid;
          } else {
            name = 'uid' + scope.$id;
            if (!hierarchialTreeService.exists(name)) {
              hierarchialTreeService.put(name);
              hierarchialTreeService.map[name].fn = function(fn, id) {
                if (id) {
                  return scope.fetch({
                    id: id,
                    fn: fn
                  });
                } else {
                  return scope.fetch({
                    id: null,
                    fn: fn
                  });
                }
              };
              scope.$watch(function() {
                return hierarchialTreeService.map[name].component;
              }, function(newvalue, oldvalue) {
                return scope.component = newvalue;
              }, true);
            }
          }
          scope.passUidToMember = name;
          fetch = function(fn, id) {
            if (id) {
              return hierarchialTreeService.map[name].fn(function(data) {
                return fn(data);
              }, id);
            } else {
              return hierarchialTreeService.map[name].fn(function(data) {
                return fn(data);
              });
            }
          };
          if (scope.id) {
            return fetch(function(data) {
              scope.list = data;
              hierarchialTreeService.map[name].list = hierarchialTreeService.map[name].list.concat(scope.list);
            }, scope.id);
          } else {
            return fetch(function(data) {
              scope.list = data;
              hierarchialTreeService.map[name].list = hierarchialTreeService.map[name].list.concat(scope.list);
            });
          }
        }
      };
    }
  ]);

  angular.module('alpCustom').directive("hierarchialTreeNode", [
    '$templateRequest', '$sce', '$compile', 'hierarchialTreeService', function($templateRequest, $sce, $compile, hierarchialTreeService) {
      return {
        restrict: "E",
        replace: true,
        scope: {
          item: '=',
          uid: '@'
        },
        controller: ["$scope", "$element", function($scope, $element) {}],
        link: function(scope, elm, attrs) {
          var indented, px, templateBegin, templateEnd, templateUrl;
          px = 20 * Number(attrs.depth);
          scope.select = function() {
            var i, _i, _len, _ref;
            _ref = hierarchialTreeService.map[scope.uid].list;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              i = _ref[_i];
              i.selected = false;
            }
            scope.item.selected = true;
            return hierarchialTreeService.map[scope.uid].component = angular.copy(scope.item);
          };
          indented = "style='position: relative; left: " + px + "px'";
          templateBegin = "<li ng-click='select()' ng-animate='tree-animate' class='tree-node' ng-class='{active: item.selected}'>";
          templateBegin += "<a>";
          templateBegin += "<i ng-show='!item.hasChildren' class='glyphicon glyphicon-file' " + indented + "></i>";
          templateBegin += "<i ng-show='item.hasChildren && !item.loaded' ng-click='load()' class='glyphicon glyphicon-plus' " + indented + "></i>";
          templateBegin += "<i ng-show='item.loaded && !item.open' ng-click='expand()' class='glyphicon glyphicon-plus' " + indented + "></i>";
          templateBegin += "<i ng-show='item.loaded && item.open' ng-click='collapse()' class='glyphicon glyphicon-minus' " + indented + "></i>";
          templateBegin += "<span class='tree-label' " + indented + ">";
          templateEnd = "</span></a></li>";
          templateUrl = $sce.getTrustedResourceUrl(attrs.content);
          $templateRequest(templateUrl).then(function(t) {
            var template;
            template = templateBegin + t + templateEnd;
            elm.html(template).show();
            $compile(elm.contents())(scope);
          }, function() {
            var template;
            console.log('error');
            template = templateBegin + "{{item}}" + templateEnd;
            elm.html(template).show();
            $compile(elm.contents())(scope);
          });
          scope.load = function() {
            var nextDepth;
            nextDepth = Number(attrs.depth) + 1;
            if (scope.item.hasChildren) {
              scope.item.loaded = true;
              scope.item.open = true;
              elm.append('<hierarchial-tree id="item.id" uid="{{uid}}" ng-show="item.open" content="' + attrs.content + '" depth={{' + nextDepth + '}}></hierarchial-tree>');
              $compile(elm.contents())(scope);
            }
          };
          scope.expand = function() {
            return scope.item.open = true;
          };
          return scope.collapse = function() {
            return scope.item.open = false;
          };
        }
      };
    }
  ]);

}).call(this);
