// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('alpCustom', []).constant('LIB_URL', (function() {
    var scriptPath, scripts;
    scripts = document.getElementsByTagName("script");
    scriptPath = scripts[scripts.length - 1].src;
    return scriptPath.substring(0, scriptPath.lastIndexOf('/') + 1);
  })());

}).call(this);
